Processing datasets/plantvillage...
Processing PlantDoc...
Processing datasets/indian_crops/Rice Leaf Disease Images...
\nData consolidation complete! The AI is ready to train on the final_dataset folder.
